name: bioinsectinet
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - rdkit
  - pip
  - pip:
      - mega.py # for uploading the results (optional)
      - pandas
      - requests
      - qrcode 
      - scikit-learn
      - torch
      - pandas
      - numpy
      - matplotlib
      - tqdm # for the progress bar
      - nltk # for the BLEU score
      - sascorer # for the SA score

